services:
  - type: web
    name: node-server
    runtime: docker
    envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: postgres-lesson11
        property: connectionString
    - key: APP_PORT
      value: 3000
    - key: APP_HOSTNAME
      value: 0.0.0.0
    - key: JWT_SECRET_KEY
      generateValue: true

    plan: free  # Change to 'starter', 'standard', etc., as needed
    buildCommand: npm install
    # startCommand: npm run start:dev
    # healthCheckPath: /
    autoDeploy: true
    # disk:
    #   name: node-src
    #   mountPath: /home/node/app/src

  - type: web
    name: adminer
    runtime: image
    image:
      url: adminer
    plan: free
    # ports:
    #   - 8080
    autoDeploy: true

databases:
  - name: postgres-lesson11
    # runtime: postgres
    plan: free
    # envVars:
    #   - fromFile: .env
    # disk:
    #   name: postgres-data
    #   mountPath: /var/lib/postgresql/data
    # healthCheckCommand: pg_isready -d postgres
    # autoDeploy: true
